# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import assignment_function_pb2 as assignment__function__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in assignment_function_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AssignmentFunctionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Assign = channel.unary_unary(
                '/accelbyte.challenge.assignmentFunction.AssignmentFunction/Assign',
                request_serializer=assignment__function__pb2.AssignmentRequest.SerializeToString,
                response_deserializer=assignment__function__pb2.AssignmentResponse.FromString,
                _registered_method=True)


class AssignmentFunctionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Assign(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AssignmentFunctionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Assign': grpc.unary_unary_rpc_method_handler(
                    servicer.Assign,
                    request_deserializer=assignment__function__pb2.AssignmentRequest.FromString,
                    response_serializer=assignment__function__pb2.AssignmentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'accelbyte.challenge.assignmentFunction.AssignmentFunction', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('accelbyte.challenge.assignmentFunction.AssignmentFunction', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AssignmentFunction(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Assign(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accelbyte.challenge.assignmentFunction.AssignmentFunction/Assign',
            assignment__function__pb2.AssignmentRequest.SerializeToString,
            assignment__function__pb2.AssignmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
